apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-server-deployment
  namespace: go-web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-web-server
  template:
    metadata:
      labels:
        app: go-web-server
    spec:
      containers:
        - image: iphun/go-hello-world:latest
          name: go-web-server
          ports:
            - containerPort: 3335
          resources:
            limits:
              cpu: "200m"
              memory: 128Mi
            requests:
              cpu: "100m"
              memory: 64Mi
