apiVersion: v1
kind: Service
metadata:
  name: go-web-server-service
  namespace: go-web-server
spec:
  selector:
    app: go-web-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3335
  type: LoadBalancer
